# 系统信息
identity:
  auth:
    logo: "https://portal.infra.linesno.com/logo.png"
    background-image: "http://data.linesno.com/banner/quora-bg-sm.webp"
    system-name: "单点登陆服务"
    banner-info: "用户一次可通过登录凭证登入会话,在该次会话期间无需再次登录"
    version: "1.0.0-SNAPSHOT"
    copyright-year: "2021-2024"
    copyright-label: "portal.infra.linesno.com 版权所有 ICP证：桂ICP备15005934号-1"
    portal-site: "http://portal.infra.linesno.com"

server:
  port: 27001

spring:
  application:
    name: alinesno-infra-base-identity-authentication
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: aip@local
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  devtools:
    restart:
      enabled: true

sms:
  redis-cache: false
  account-max: 20
  minute-max: 2
  config-type: yaml
  is-print: false
  corePoolSize: 10
  maxPoolSize: 30
  queueCapacity: 50
  shutdownStrategy: true
  is-dev: true
  blends:
    alibaba:
      accessKeyId:
      accessKeySecret:
      signature:
      templateId:
      templateName: code

forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒

alinesno.infra:
  authority:
    host: "http://localhost:30100"

ip2region:
  external: false
  index-block-size: 4096
  total-header-size: 8192
  location: classpath*:ip2region/ip2region.db

sa-token:
  sso:
    allow-url: "*"
    ticket-timeout: 300
    is-http: true
  is-print: false
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
