# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Create Nexus Config File
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > nexus-config.xml
          echo '<settings>' >> nexus-config.xml

          echo '  <servers>' >> nexus-config.xml
          echo '    <server>' >> nexus-config.xml
          echo '      <id>rdc-releases</id>' >> nexus-config.xml
          echo '      <username>${{ secrets.NEXUS_USERNAME }}</username>' >> nexus-config.xml
          echo '      <password>${{ secrets.NEXUS_PASSWORD }}</password>' >> nexus-config.xml
          echo '    </server>' >> nexus-config.xml
          echo '    <server>' >> nexus-config.xml
          echo '      <id>rdc-snapshots</id>' >> nexus-config.xml
          echo '      <username>${{ secrets.NEXUS_USERNAME }}</username>' >> nexus-config.xml
          echo '      <password>${{ secrets.NEXUS_PASSWORD }}</password>' >> nexus-config.xml
          echo '    </server>' >> nexus-config.xml
          echo '  </servers>' >> nexus-config.xml

          echo '  <mirrors>' >> nexus-config.xml
          echo '    <mirror>' >> nexus-config.xml
          echo '      <id>mirror</id>' >> nexus-config.xml
          echo '      <mirrorOf>central,jcenter,!rdc-releases,!rdc-snapshots</mirrorOf>' >> nexus-config.xml
          echo '      <name>mirror</name>' >> nexus-config.xml
          echo '      <url>https://repo.maven.apache.org/maven2</url>' >> nexus-config.xml
          echo '    </mirror>' >> nexus-config.xml
          echo '    <mirror>' >> nexus-config.xml
          echo '      <id>rdc-releases</id>' >> nexus-config.xml
          echo '      <mirrorOf>releases</mirrorOf>' >> nexus-config.xml
          echo '      <url>http://repo.infra.linesno.com/nexus/content/repositories/releases/</url>' >> nexus-config.xml
          echo '    </mirror>' >> nexus-config.xml
          echo '    <mirror>' >> nexus-config.xml
          echo '      <id>rdc-snapshots</id>' >> nexus-config.xml
          echo '      <mirrorOf>snapshots</mirrorOf>' >> nexus-config.xml
          echo '      <url>http://repo.infra.linesno.com/nexus/content/repositories/snapshots/</url>' >> nexus-config.xml
          echo '    </mirror>' >> nexus-config.xml
          echo '  </mirrors>' >> nexus-config.xml 

          echo '  <profiles>' >> nexus-config.xml
          echo '    <profile>' >> nexus-config.xml
          echo '      <id>rdc</id>' >> nexus-config.xml
          echo '      <properties>' >> nexus-config.xml
          echo '        <altReleaseDeploymentRepository>' >> nexus-config.xml
          echo '          rdc-releases::default::http://repo.infra.linesno.com/nexus/content/repositories/releases/' >> nexus-config.xml
          echo '        </altReleaseDeploymentRepository>' >> nexus-config.xml
          echo '        <altSnapshotDeploymentRepository>' >> nexus-config.xml
          echo '          rdc-snapshots::default::http://repo.infra.linesno.com/nexus/content/repositories/snapshots/' >> nexus-config.xml
          echo '        </altSnapshotDeploymentRepository>' >> nexus-config.xml
          echo '      </properties>' >> nexus-config.xml
          echo '      <repositories>' >> nexus-config.xml
          echo '        <repository>' >> nexus-config.xml
          echo '          <id>central</id>' >> nexus-config.xml
          echo '          <url>https://repo.maven.apache.org/maven2</url>' >> nexus-config.xml
          echo '          <releases>' >> nexus-config.xml
          echo '            <enabled>true</enabled>' >> nexus-config.xml
          echo '          </releases>' >> nexus-config.xml
          echo '          <snapshots>' >> nexus-config.xml
          echo '            <enabled>false</enabled>' >> nexus-config.xml
          echo '          </snapshots>' >> nexus-config.xml
          echo '        </repository>' >> nexus-config.xml
          echo '        <repository>' >> nexus-config.xml
          echo '          <id>snapshots</id>' >> nexus-config.xml
          echo '          <url>https://repo.maven.apache.org/maven2</url>' >> nexus-config.xml
          echo '          <releases>' >> nexus-config.xml
          echo '            <enabled>false</enabled>' >> nexus-config.xml
          echo '          </releases>' >> nexus-config.xml
          echo '          <snapshots>' >> nexus-config.xml
          echo '            <enabled>true</enabled>' >> nexus-config.xml
          echo '          </snapshots>' >> nexus-config.xml
          echo '        </repository>' >> nexus-config.xml
          echo '        <repository>' >> nexus-config.xml
          echo '          <id>rdc-releases</id>' >> nexus-config.xml
          echo '          <url>http://repo.infra.linesno.com/nexus/content/repositories/releases/</url>' >> nexus-config.xml
          echo '          <releases>' >> nexus-config.xml
          echo '            <enabled>true</enabled>' >> nexus-config.xml
          echo '          </releases>' >> nexus-config.xml
          echo '          <snapshots>' >> nexus-config.xml
          echo '            <enabled>false</enabled>' >> nexus-config.xml
          echo '          </snapshots>' >> nexus-config.xml
          echo '        </repository>' >> nexus-config.xml
          echo '        <repository>' >> nexus-config.xml
          echo '          <id>rdc-snapshots</id>' >> nexus-config.xml
          echo '          <url>http://repo.infra.linesno.com/nexus/content/repositories/snapshots/</url>' >> nexus-config.xml
          echo '          <releases>' >> nexus-config.xml
          echo '            <enabled>false</enabled>' >> nexus-config.xml
          echo '          </releases>' >> nexus-config.xml
          echo '          <snapshots>' >> nexus-config.xml
          echo '            <enabled>true</enabled>' >> nexus-config.xml
          echo '          </snapshots>' >> nexus-config.xml
          echo '        </repository>' >> nexus-config.xml
          echo '      </repositories> ' >> nexus-config.xml
          echo '    </profile>' >> nexus-config.xml
          echo '  </profiles>' >> nexus-config.xml

          echo '  <activeProfiles>' >> nexus-config.xml
          echo '    <activeProfile>rdc</activeProfile>' >> nexus-config.xml
          echo '  </activeProfiles>' >> nexus-config.xml
          echo '</settings>' >> nexus-config.xml

      - name: Build and Deploy to Nexus
        run: mvn clean deploy --settings nexus-config.xml
