# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

	  - name: Create Nexus Config File
		run: |
			echo '<?xml version="1.0" encoding="UTF-8"?>' > nexus-config.xml
			echo '<settings>' >> nexus-config.xml
			echo '  <servers>' >> nexus-config.xml
			echo '    <server>' >> nexus-config.xml
			echo '      <id>internal.repo</id>' >> nexus-config.xml
			echo '      <username>${{ secrets.NEXUS_USERNAME }}</username>' >> nexus-config.xml
			echo '      <password>${{ secrets.NEXUS_PASSWORD }}</password>' >> nexus-config.xml
			echo '    </server>' >> nexus-config.xml
			echo '  </servers>' >> nexus-config.xml
			echo '  <mirrors>' >> nexus-config.xml
			echo '    <mirror>' >> nexus-config.xml
			echo '      <id>mirror</id>' >> nexus-config.xml
			echo '      <mirrorOf>central,jcenter,!rdc-releases,!rdc-snapshots</mirrorOf>' >> nexus-config.xml
			echo '      <name>mirror</name>' >> nexus-config.xml
			echo '      <url>https://maven.aliyun.com/nexus/content/groups/public</url>' >> nexus-config.xml
			echo '    </mirror>' >> nexus-config.xml
			echo '    <mirror>' >> nexus-config.xml
			echo '      <id>rdc-releases</id>' >> nexus-config.xml
			echo '      <mirrorOf>releases</mirrorOf>' >> nexus-config.xml
			echo '      <url>http://repo.infra.linesno.com/nexus/content/repositories/releases/</url>' >> nexus-config.xml
			echo '    </mirror>' >> nexus-config.xml
			echo '    <mirror>' >> nexus-config.xml
			echo '      <id>rdc-snapshots</id>' >> nexus-config.xml
			echo '      <mirrorOf>snapshots</mirrorOf>' >> nexus-config.xml
			echo '      <url>http://repo.infra.linesno.com/nexus/content/repositories/snapshots/</url>' >> nexus-config.xml
			echo '    </mirror>' >> nexus-config.xml
			echo '  </mirrors>' >> nexus-config.xml
			echo '</settings>' >> nexus-config.xml

      - name: Build with Maven
        run: mvn -B clean deploy --settings nexus-config.xml

      - name: Build and Deploy to Nexus
        run: mvn clean deploy --settings nexus-config.xml
